version: '3.0'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - db
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=fog_broker
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db/db_script.sql:/docker-entrypoint-initdb.d/db_script.sql

volumes:
  postgres_data:
