apiVersion: v1
kind: Service
metadata:
  name: {{ include "nebulous-cloud-fog-service-broker.fullname" . }}
  labels:
    {{- include "nebulous-cloud-fog-service-broker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.guiPort }}
      targetPort: http
      protocol: TCP
      name: gui
  selector:
    {{- include "nebulous-cloud-fog-service-broker.selectorLabels" . | nindent 4 }}
